### ISSUE TITLE
question: git commits and repo

### ISSUE THREAD

**Issue by climateamante** [Rapdash/bank-crud-backend#1]
@Rapdash can you confirm that your work is uploaded to the current repo?
I am not seeing any code or commits.

Also, thank you for updating your project board.

**Comment by FritzTheDev** [comment]
@climateamante Thanks for the reminder. Just pushed what I've got, I'd been putting off getting it onto github.
As an update re: why there hasn't been any progress over the last two hours of work, I've been reading up on django best practices & structure. Analysis paralysis is setting in, so I'm going to get back to execution as soon as I finish this response.
Closing this issue.
